array_horizontal_layout_threshold = 1000
fn_call_width = 100
reorder_extern_crates = true
reorder_extern_crates_in_group = true
reorder_imports = true
reorder_imports_in_group = true
reorder_imported_names = true
reorder_modules = true
